Fix compatibility with NPM
aeternity/aepp-boilerplate-vue pull request #17
Opened 2022-07-28 09:17 UTC by davidyuk

2022-07-28 09:24 UTC, davidyuk commented on package.json
> -    "@vue/eslint-plugin": "^4.2.0",
This package was causing instalation issue, it is 5 years old, was used before @vue/cli

2022-07-28 09:24 UTC, davidyuk commented on package.json
> -    "@vue/eslint-config-standard": "^8.0.0",
This config wasn't enabled, and I removed it completely, keeping only rules for error prevention.

2022-07-28 09:24 UTC, davidyuk commented on package.json
> -      "git add"
Vue cli generate this part without this line, so it looks like it can be omitted 🤔

2022-07-28 16:48 UTC, marc0olo commented
@davidyuk I was shortly playing around with fixing tests etc. but this is a mess for me. can you check the tests and maybe fix or delete the unnecessary and unused stuff, too? 😅

2022-07-29 15:15 UTC, thepiwo approved these changes

2022-07-29 15:19 UTC, thepiwo requested changes
readme still states yarn usage

2022-07-29 16:00 UTC, thepiwo commented
replaced by this one https://github.com/aeternity/aepp-boilerplate-vue/pull/18

2022-07-29 16:00 UTC, closed without merging